# Generated by Django 3.2.6 on 2021-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cay', models.CharField(default=None, max_length=20, verbose_name='CAY')),
                ('caym1', models.CharField(default=None, max_length=20, null=True, verbose_name='CAYM1')),
                ('caym2', models.CharField(default=None, max_length=20, null=True, verbose_name='CAYM2')),
            ],
        ),
    ]
